In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [18]:
df = pd.read_csv('/home/keith/Springboard/LoanStats3d.csv', low_memory = False, skiprows = [0,2])

In [19]:
df.shape

(421096, 111)

In [20]:
df.dtypes

id                                 object
member_id                         float64
loan_amnt                         float64
funded_amnt                       float64
funded_amnt_inv                   float64
term                               object
int_rate                           object
installment                       float64
grade                              object
sub_grade                          object
emp_title                          object
emp_length                         object
home_ownership                     object
annual_inc                        float64
verification_status                object
issue_d                            object
loan_status                        object
pymnt_plan                         object
url                               float64
desc                               object
purpose                            object
title                              object
zip_code                           object
addr_state                         object
dti                               float64
delinq_2yrs                       float64
earliest_cr_line                   object
inq_last_6mths                    float64
mths_since_last_delinq            float64
mths_since_last_record            float64
                                   ...
mo_sin_old_rev_tl_op              float64
mo_sin_rcnt_rev_tl_op             float64
mo_sin_rcnt_tl                    float64
mort_acc                          float64
mths_since_recent_bc              float64
mths_since_recent_bc_dlq          float64
mths_since_recent_inq             float64
mths_since_recent_revol_delinq    float64
num_accts_ever_120_pd             float64
num_actv_bc_tl                    float64
num_actv_rev_tl                   float64
num_bc_sats                       float64
num_bc_tl                         float64
num_il_tl                         float64
num_op_rev_tl                     float64
num_rev_accts                     float64
num_rev_tl_bal_gt_0               float64
num_sats                          float64
num_tl_120dpd_2m                  float64
num_tl_30dpd                      float64
num_tl_90g_dpd_24m                float64
num_tl_op_past_12m                float64
pct_tl_nvr_dlq                    float64
percent_bc_gt_75                  float64
pub_rec_bankruptcies              float64
tax_liens                         float64
tot_hi_cred_lim                   float64
total_bal_ex_mort                 float64
total_bc_limit                    float64
total_il_high_credit_limit        float64
dtype: object

In [21]:
df.head(10)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,NaN,NaN,15000.0,15000.0,15000.0,36 months,8.49%,473.45,B,B1,...,0.0,4.0,100.0,20.0,1.0,0.0,369112.0,27849.0,28200.0,21124.0
1,NaN,NaN,8000.0,8000.0,8000.0,36 months,10.78%,261.08,B,B4,...,0.0,4.0,97.1,100.0,0.0,0.0,168819.0,148154.0,5800.0,136996.0
2,NaN,NaN,15000.0,15000.0,15000.0,36 months,10.78%,489.52,B,B4,...,0.0,2.0,100.0,100.0,0.0,0.0,16300.0,12272.0,10300.0,0.0
3,NaN,NaN,25000.0,25000.0,25000.0,60 months,11.48%,549.57,B,B5,...,0.0,4.0,97.0,0.0,0.0,0.0,72150.0,23522.0,45800.0,17750.0
4,NaN,NaN,12000.0,12000.0,12000.0,36 months,5.32%,361.38,A,A1,...,0.0,1.0,94.7,0.0,0.0,0.0,183062.0,11146.0,8500.0,29053.0
5,NaN,NaN,5000.0,5000.0,5000.0,36 months,7.91%,156.48,A,A5,...,0.0,0.0,100.0,0.0,1.0,0.0,21690.0,11665.0,10100.0,8190.0
6,NaN,NaN,18500.0,18500.0,18500.0,60 months,12.88%,419.80,C,C2,...,0.0,3.0,89.5,16.7,0.0,0.0,143748.0,28564.0,27500.0,17944.0
7,NaN,NaN,15000.0,15000.0,15000.0,60 months,13.44%,344.69,C,C3,...,0.0,2.0,100.0,40.0,1.0,0.0,176208.0,155521.0,13800.0,95668.0
8,NaN,NaN,17925.0,17925.0,17925.0,60 months,17.27%,448.09,D,D3,...,0.0,0.0,100.0,66.7,0.0,0.0,122214.0,39544.0,12400.0,26199.0
9,NaN,NaN,10000.0,10000.0,10000.0,36 months,11.48%,329.67,B,B5,...,0.0,2.0,100.0,33.3,0.0,1.0,49732.0,23197.0,20800.0,27132.0

In [22]:
df.tail(10)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
421086,NaN,NaN,7500.0,7500.0,7500.0,36 months,9.49%,240.22,B,B2,...,0.0,4.0,96.6,20.0,1.0,0.0,36320.0,18611.0,10700.0,21820.0
421087,NaN,NaN,11575.0,11575.0,11575.0,36 months,15.59%,404.61,D,D1,...,0.0,1.0,100.0,42.9,0.0,0.0,29866.0,19798.0,27500.0,1766.0
421088,NaN,NaN,12000.0,12000.0,12000.0,36 months,11.99%,398.52,B,B5,...,1.0,3.0,98.3,50.0,0.0,0.0,325484.0,112990.0,15400.0,98125.0
421089,NaN,NaN,10000.0,10000.0,10000.0,36 months,11.99%,332.10,B,B5,...,0.0,1.0,100.0,100.0,0.0,0.0,32950.0,25274.0,9200.0,15850.0
421090,NaN,NaN,24000.0,24000.0,24000.0,36 months,11.99%,797.03,B,B5,...,0.0,2.0,56.5,100.0,0.0,0.0,152650.0,8621.0,9000.0,0.0
421091,NaN,NaN,12000.0,12000.0,12000.0,60 months,19.99%,317.86,E,E3,...,1.0,2.0,95.0,66.7,0.0,0.0,96919.0,58418.0,9700.0,69919.0
421092,NaN,NaN,13000.0,13000.0,13000.0,60 months,15.99%,316.07,D,D2,...,0.0,3.0,100.0,50.0,1.0,0.0,51239.0,34178.0,10600.0,33239.0
421093,NaN,NaN,20000.0,20000.0,20000.0,36 months,11.99%,664.20,B,B5,...,0.0,1.0,100.0,50.0,0.0,1.0,43740.0,33307.0,41700.0,0.0
421094,Total amount funded in policy code 1: 6417608175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421095,Total amount funded in policy code 2: 1944088810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df1 = df.drop([421094, 421095])
df1

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,NaN,NaN,15000.0,15000.0,15000.0,36 months,8.49%,473.45,B,B1,...,0.0,4.0,100.0,20.0,1.0,0.0,369112.0,27849.0,28200.0,21124.0
1,NaN,NaN,8000.0,8000.0,8000.0,36 months,10.78%,261.08,B,B4,...,0.0,4.0,97.1,100.0,0.0,0.0,168819.0,148154.0,5800.0,136996.0
2,NaN,NaN,15000.0,15000.0,15000.0,36 months,10.78%,489.52,B,B4,...,0.0,2.0,100.0,100.0,0.0,0.0,16300.0,12272.0,10300.0,0.0
3,NaN,NaN,25000.0,25000.0,25000.0,60 months,11.48%,549.57,B,B5,...,0.0,4.0,97.0,0.0,0.0,0.0,72150.0,23522.0,45800.0,17750.0
4,NaN,NaN,12000.0,12000.0,12000.0,36 months,5.32%,361.38,A,A1,...,0.0,1.0,94.7,0.0,0.0,0.0,183062.0,11146.0,8500.0,29053.0
5,NaN,NaN,5000.0,5000.0,5000.0,36 months,7.91%,156.48,A,A5,...,0.0,0.0,100.0,0.0,1.0,0.0,21690.0,11665.0,10100.0,8190.0
6,NaN,NaN,18500.0,18500.0,18500.0,60 months,12.88%,419.80,C,C2,...,0.0,3.0,89.5,16.7,0.0,0.0,143748.0,28564.0,27500.0,17944.0
7,NaN,NaN,15000.0,15000.0,15000.0,60 months,13.44%,344.69,C,C3,...,0.0,2.0,100.0,40.0,1.0,0.0,176208.0,155521.0,13800.0,95668.0
8,NaN,NaN,17925.0,17925.0,17925.0,60 months,17.27%,448.09,D,D3,...,0.0,0.0,100.0,66.7,0.0,0.0,122214.0,39544.0,12400.0,26199.0
9,NaN,NaN,10000.0,10000.0,10000.0,36 months,11.48%,329.67,B,B5,...,0.0,2.0,100.0,33.3,0.0,1.0,49732.0,23197.0,20800.0,27132.0
10,NaN,NaN,14000.0,14000.0,14000.0,36 months,9.80%,450.43,B,B3,...,0.0,2.0,100.0,0.0,0.0,0.0,531602.0,84039.0,34500.0,55842.0
11,NaN,NaN,15000.0,15000.0,15000.0,36 months,9.80%,482.61,B,B3,...,0.0,4.0,100.0,0.0,1.0,0.0,347470.0,53397.0,36100.0,47370.0
12,NaN,NaN,24700.0,24700.0,24700.0,36 months,11.99%,820.28,C,C1,...,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0
13,NaN,NaN,3600.0,3600.0,3600.0,36 months,13.99%,123.03,C,C4,...,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0
14,NaN,NaN,28000.0,28000.0,28000.0,36 months,13.44%,949.38,C,C3,...,0.0,0.0,100.0,40.0,0.0,0.0,36100.0,22780.0,29000.0,0.0
15,NaN,NaN,20000.0,20000.0,20000.0,36 months,5.32%,602.30,A,A1,...,0.0,0.0,100.0,0.0,0.0,0.0,106217.0,15444.0,76200.0,30017.0
16,NaN,NaN,15000.0,15000.0,15000.0,36 months,5.32%,451.73,A,A1,...,0.0,0.0,90.5,0.0,0.0,0.0,33800.0,17003.0,14300.0,0.0
17,NaN,NaN,17600.0,17600.0,17600.0,36 months,5.32%,530.03,A,A1,...,0.0,1.0,100.0,0.0,0.0,0.0,285027.0,80847.0,23600.0,92701.0
18,NaN,NaN,6000.0,6000.0,6000.0,36 months,7.49%,186.61,A,A4,...,0.0,0.0,93.7,50.0,0.0,0.0,156354.0,22741.0,3800.0,36083.0
19,NaN,NaN,16000.0,16000.0,16000.0,60 months,17.97%,406.04,D,D4,...,0.0,3.0,100.0,100.0,0.0,0.0,228050.0,63158.0,15800.0,22000.0
20,NaN,NaN,16000.0,16000.0,16000.0,36 months,12.88%,538.18,C,C2,...,0.0,2.0,80.0,0.0,0.0,1.0,80999.0,39781.0,4700.0,71499.0
21,NaN,NaN,21000.0,21000.0,21000.0,60 months,13.99%,488.53,C,C4,...,0.0,1.0,100.0,75.0,0.0,0.0,370357.0,372407.0,23300.0,347057.0
22,NaN,NaN,16800.0,16800.0,16800.0,60 months,12.88%,381.23,C,C2,...,0.0,1.0,64.4,25.0,0.0,0.0,412771.0,75808.0,12600.0,115941.0
23,NaN,NaN,16000.0,16000.0,16000.0,60 months,13.99%,372.21,C,C4,...,0.0,0.0,73.7,25.0,0.0,2.0,704224.0,112166.0,5100.0,124120.0
24,NaN,NaN,8650.0,8650.0,8650.0,36 months,5.32%,260.50,A,A1,...,0.0,1.0,100.0,0.0,0.0,0.0,191618.0,31199.0,18300.0,27078.0
25,NaN,NaN,20000.0,20000.0,20000.0,36 months,9.80%,643.47,B,B3,...,0.0,5.0,92.3,0.0,0.0,0.0,117477.0,40090.0,51600.0,38577.0
26,NaN,NaN,2500.0,2500.0,2500.0,36 months,17.27%,89.47,D,D3,...,1.0,3.0,68.4,0.0,0.0,0.0,196429.0,197169.0,700.0,193929.0
27,NaN,NaN,7200.0,7200.0,7200.0,36 months,15.77%,252.32,D,D1,...,0.0,3.0,97.7,50.0,0.0,1.0,255047.0,275831.0,6700.0,246447.0
28,NaN,NaN,21000.0,21000.0,21000.0,60 months,13.44%,482.56,C,C3,...,0.0,0.0,100.0,50.0,1.0,0.0,57564.0,51489.0,5900.0,51664.0
29,NaN,NaN,15700.0,15700.0,15700.0,60 months,16.59%,386.74,D,D2,...,0.0,3.0,96.4,75.0,0.0,0.0,305962.0,83774.0,12300.0,81126.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421064,NaN,NaN,13000.0,13000.0,13000.0,36 months,8.19%,408.52,A,A5,...,0.0,0.0,88.0,66.7,0.0,0.0,251426.0,19133.0,6500.0,20950.0
421065,NaN,NaN,15000.0,15000.0,15000.0,36 months,11.99%,498.15,B,B5,...,0.0,0.0,100.0,100.0,0.0,0.0,17081.0,15724.0,9600.0,7381.0
421066,NaN,NaN,4200.0,4200.0,4200.0,36 months,15.99%,147.64,D,D2,...,0.0,6.0,88.9,100.0,0.0,0.0,224211.0,45512.0,5600.0,40401.0
421067,NaN,NaN,10300.0,10300.0,10300.0,60 months,13.66%,237.86,C,C3,...,0.0,2.0,95.8,42.9,0.0,0.0,58710.0,41956.0,17100.0,36710.0
421068,NaN,NaN,15000.0,15000.0,15000.0,60 months,11.44%,329.44,B,B4,...,0.0,2.0,100.0,40.0,0.0,0.0,47674.0,33529.0,22500.0,21574.0
421069,NaN,NaN,26950.0,26950.0,26950.0,36 months,8.19%,846.88,A,A5,...,0.0,0.0,100.0,0.0,0.0,0.0,137433.0,41650.0,124600.0,8333.0
421070,NaN,NaN,18700.0,18700.0,18700.0,60 months,17.86%,473.44,D,D5,...,0.0,3.0,88.9,50.0,0.0,0.0,42499.0,40164.0,10000.0,32299.0
421071,NaN,NaN,23000.0,23000.0,23000.0,60 months,15.59%,554.32,D,D1,...,0.0,2.0,100.0,37.5,0.0,0.0,79510.0,48978.0,60800.0,13910.0
421072,NaN,NaN,6000.0,6000.0,6000.0,36 months,17.86%,216.50,D,D5,...,0.0,2.0,100.0,100.0,0.0,0.0,412963.0,14906.0,1900.0,8085.0
421073,NaN,NaN,25000.0,25000.0,25000.0,60 months,15.59%,602.52,D,D1,...,0.0,1.0,100.0,37.5,0.0,0.0,24400.0,13860.0,20900.0,0.0
421074,NaN,NaN,25000.0,25000.0,25000.0,60 months,15.99%,607.82,D,D2,...,0.0,0.0,100.0,100.0,0.0,0.0,18700.0,17275.0,17500.0,0.0
421075,NaN,NaN,26500.0,26500.0,26500.0,60 months,8.67%,545.87,B,B1,...,0.0,0.0,95.2,50.0,0.0,0.0,214551.0,91768.0,67600.0,33501.0
421076,NaN,NaN,8000.0,8000.0,8000.0,36 months,8.19%,251.40,A,A5,...,0.0,2.0,85.2,33.3,0.0,0.0,230732.0,38259.0,5800.0,39940.0
421077,NaN,NaN,21000.0,21000.0,21000.0,36 months,6.03%,639.15,A,A1,...,0.0,0.0,100.0,0.0,0.0,0.0,301457.0,36303.0,76300.0,36656.0
421078,NaN,NaN,10775.0,10775.0,10775.0,36 months,6.03%,327.95,A,A1,...,0.0,0.0,90.5,0.0,0.0,0.0,60948.0,24696.0,38700.0,19248.0
421079,NaN,NaN,12000.0,12000.0,12000.0,36 months,9.49%,384.34,B,B2,...,1.0,1.0,80.0,40.0,0.0,0.0,28183.0,20671.0,10500.0,16283.0
421080,NaN,NaN,10000.0,10000.0,10000.0,36 months,6.49%,306.45,A,A2,...,0.0,0.0,96.9,0.0,0.0,0.0,148298.0,88120.0,30300.0,117998.0
421081,NaN,NaN,13150.0,13150.0,13150.0,60 months,14.99%,312.77,C,C5,...,0.0,0.0,100.0,0.0,0.0,0.0,190700.0,672.0,20700.0,0.0
421082,NaN,NaN,6225.0,6225.0,6225.0,36 months,16.49%,220.37,D,D3,...,0.0,0.0,100.0,100.0,0.0,0.0,14307.0,8357.0,1800.0,12507.0
421083,NaN,NaN,7000.0,7000.0,7000.0,36 months,14.31%,240.30,C,C4,...,1.0,3.0,80.0,16.7,0.0,2.0,43768.0,32135.0,6900.0,33868.0
421084,NaN,NaN,4000.0,4000.0,4000.0,36 months,8.67%,126.59,B,B1,...,0.0,2.0,100.0,0.0,1.0,0.0,58334.0,18979.0,12900.0,28234.0
421085,NaN,NaN,10850.0,10850.0,10850.0,36 months,19.24%,399.04,E,E2,...,0.0,3.0,90.0,50.0,0.0,0.0,81797.0,28301.0,2500.0,27533.0
421086,NaN,NaN,7500.0,7500.0,7500.0,36 months,9.49%,240.22,B,B2,...,0.0,4.0,96.6,20.0,1.0,0.0,36320.0,18611.0,10700.0,21820.0
421087,NaN,NaN,11575.0,11575.0,11575.0,36 months,15.59%,404.61,D,D1,...,0.0,1.0,100.0,42.9,0.0,0.0,29866.0,19798.0,27500.0,1766.0
421088,NaN,NaN,12000.0,12000.0,12000.0,36 months,11.99%,398.52,B,B5,...,1.0,3.0,98.3,50.0,0.0,0.0,325484.0,112990.0,15400.0,98125.0
421089,NaN,NaN,10000.0,10000.0,10000.0,36 months,11.99%,332.10,B,B5,...,0.0,1.0,100.0,100.0,0.0,0.0,32950.0,25274.0,9200.0,15850.0
421090,NaN,NaN,24000.0,24000.0,24000.0,36 months,11.99%,797.03,B,B5,...,0.0,2.0,56.5,100.0,0.0,0.0,152650.0,8621.0,9000.0,0.0
421091,NaN,NaN,12000.0,12000.0,12000.0,60 months,19.99%,317.86,E,E3,...,1.0,2.0,95.0,66.7,0.0,0.0,96919.0,58418.0,9700.0,69919.0
421092,NaN,NaN,13000.0,13000.0,13000.0,60 months,15.99%,316.07,D,D2,...,0.0,3.0,100.0,50.0,1.0,0.0,51239.0,34178.0,10600.0,33239.0
421093,NaN,NaN,20000.0,20000.0,20000.0,36 months,11.99%,664.20,B,B5,...,0.0,1.0,100.0,50.0,0.0,1.0,43740.0,33307.0,41700.0,0.0

In [29]:
df1['loan_amnt'].unique()

array([ 15000.,   8000.,  25000., ...,  34525.,   1625.,  30275.])

In [30]:
df1['term'].unique()

array([' 36 months', ' 60 months'], dtype=object)

In [31]:
df1['loan_status'].unique()

array(['Fully Paid', 'Current', 'Late (31-120 days)', 'Charged Off',
       'Late (16-30 days)', 'In Grace Period', 'Default'], dtype=object)

In [32]:
df1['emp_length'].unique()

array(['6 years', '< 1 year', '1 year', '10+ years', '4 years', '2 years',
       '3 years', '9 years', '5 years', 'n/a', '7 years', '8 years'], dtype=object)

id                                 object
member_id                         float64
loan_amnt                         float64
funded_amnt                       float64
funded_amnt_inv                   float64
term                               object
int_rate                           object
installment                       float64
grade                              object
sub_grade                          object
emp_title                          object
emp_length                         object
home_ownership                     object
annual_inc                        float64
verification_status                object
issue_d                            object
loan_status                        object
pymnt_plan                         object
url                               float64
desc                               object
purpose                            object
title                              object
zip_code                           object
addr_state                         object
dti                               float64
delinq_2yrs                       float64
earliest_cr_line                   object
inq_last_6mths                    float64
mths_since_last_delinq            float64
mths_since_last_record            float64
                                   ...
mo_sin_old_rev_tl_op              float64
mo_sin_rcnt_rev_tl_op             float64
mo_sin_rcnt_tl                    float64
mort_acc                          float64
mths_since_recent_bc              float64
mths_since_recent_bc_dlq          float64
mths_since_recent_inq             float64
mths_since_recent_revol_delinq    float64
num_accts_ever_120_pd             float64
num_actv_bc_tl                    float64
num_actv_rev_tl                   float64
num_bc_sats                       float64
num_bc_tl                         float64
num_il_tl                         float64
num_op_rev_tl                     float64
num_rev_accts                     float64
num_rev_tl_bal_gt_0               float64
num_sats                          float64
num_tl_120dpd_2m                  float64
num_tl_30dpd                      float64
num_tl_90g_dpd_24m                float64
num_tl_op_past_12m                float64
pct_tl_nvr_dlq                    float64
percent_bc_gt_75                  float64
pub_rec_bankruptcies              float64
tax_liens                         float64
tot_hi_cred_lim                   float64
total_bal_ex_mort                 float64
total_bc_limit                    float64
total_il_high_credit_limit        float64
dtype: object